name: list_curitiba
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  dartz: ^0.10.0
  flutter_modular: ^3.1.1+1
  cloud_firestore: ^4.3.1
  http: ^0.13.3
  mobx: ^2.0.1
  build_runner: ^2.0.5
  flutter_mobx: ^2.0.0
  mobx_codegen: ^2.0.1+3
  uuid: ^3.0.5
  intl: ^0.17.0







  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


